services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app_network
      
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      KAFKA_ZOOKEEPERCONNECT: "zookeeper:2181"
    ports:
      - "9000:9000"
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consulta_credito
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./Consulta-Credito-Api
      dockerfile: Dockerfile
    container_name: consulta-credito-api
    entrypoint: [ "sh", "-c", "sleep 15 && java -jar app.jar" ]
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/consulta_credito
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8090:8090"
    networks:
      - app_network

  frontend:
    build:
      context: ./Consulta-Credito-Web
      dockerfile: Dockerfile
    container_name: consulta-credito-web
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
